---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine" tag="latest"
    - image="alpine" tag="edge"
    - image="amazonlinux" tag="1"
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="debian" tag="bullseye"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"
    - image="ubuntu" tag="xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - n=0 ; until [ "$n" = 3 ] ; do tox --parallel all && break ; n=$((n+1)) ; done

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "w98ZMORIwKiwF1th2jMJPRKhJZmKHuk2OflPCktQi/3lhy+MPsY7jlDPhlW91rVIyh9/FkJjAb8PVF4On1JBzn6XRILXH+CKbzzvNWUySr72dBx1aea9NvIfPr4ag3xBMBXbpP+zJ6S465q16oE9GP0GFDJq1UQRhjvtT/SiAurwe2jLlIyJ4++kgUkxC0fHJ29hXRYym+jYlFFmvzT7vi4xzNFECMP03AcYahE8MxN+K2CH5+9ZuGxpxmeDxmeJR72Ldl3KH6FU12BxCoja5xNBoNVZXO50KkgBoQwl2sx9+s9uqHghAWotwfAWJGM7sP5dTNbnuwJ5bpgE/ik94rypxiu8+wjSnC3gBGkDgooaToLfrBQrbvLkdBOYYaopJu3Hgl8B8ucXbDjJK51AUwdQLK2y6JoAZrxveyDE90PAUUw91fTqJTKyVp6XcpjToCDF4sUZ14/beiIlV+J6Yh13kewHdxbASlNgqbGcDbO6uYetYaxuTEqpq7xg7jgVAItwFQJFDbgkDby1Kczzr3YQUJ6Ca/m29B6Srb8tkMe0itzRBx9HOh1ruobYsFkkMFEVxeyWhp5IKArSBTOXBwQz0GoJuBbUeSKgPACrVLopxz+XYRHCDyKQJAU2Ya+E3KuwQkN1fXQkVtxgeLeWzIaeXHBhlmOxaB5zsO4aW84="
  email: false
