---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes
  vars:
    _collectd_postgres_plugin_dependencies:
      default:
        - collectd-postgresql
      Suse:
        - collectd-plugin-postgresql
      Debian: []
    _collectd_write_http_dependencies:
      default: []
      Alpine:
        - collectd-write_http
      RedHat:
        - collectd-write_http
    collectd_plugin_logging: logfile
    collectd_basic_plugins:
      - cpu
      - interface
      - load
      - memory
    collectd_plugins:
      - name: write_http
        dependencies: "{{ _collectd_write_http_dependencies[ansible_os_family] | default(_collectd_write_http_dependencies['default']) }}"
        config: |
          <Node "test">
            URL "127.0.0.1:8080/test.collectd"
            Format "JSON"
            StoreRates true
          </Node>
      - name: postgresql
        dependencies: "{{ _collectd_postgres_plugin_dependencies[ansible_os_family] | default(_collectd_postgres_plugin_dependencies['default']) }}"
        config: |
          <Query tickets>
            Statement "SELECT count(t.id) AS count FROM tickets t WHERE t.closed is null;"
            <Result>
              Type gauge
              InstancePrefix "tickets"
              ValuesFrom "count"
            </Result>
          </Query>
          <Database "test">
            Host "psql-database.hostname.com"
            Port "5432"
            User "my_psqladminuser"
            Password "my_passwd"
            SSLMode "prefer"
            Query tickets
          </Database>
  roles:
    - role: ansible-role-collectd
